# 🐍 **Week 12 Supplement 1: NumPy — Full Tutorial**

Welcome to the **NumPy supplement** for Week 12! 🎓

NumPy (**Num**erical **Py**thon) is the foundation library for numerical computing in Python. Pandas, Matplotlib, scikit-learn, and most data/science libraries are built on top of it — so mastering NumPy makes everything after it easier.

In this notebook you will learn:
1. What NumPy is and why we use it
2. Creating arrays
3. Array attributes (shape, dtype, ndim)
4. Indexing and slicing
5. Reshaping arrays
6. Array arithmetic and broadcasting
7. Mathematical & statistical functions
8. Linear algebra basics
9. Random numbers with `np.random`
10. Stacking, splitting, sorting, and searching
11. Saving and loading arrays
12. 🏭 Hands-on exercise: Factory sensor data with NumPy
13. Practice exercises

Let's dive in! 🚀

## 📌 **1. What is NumPy and Why Use It?**

### 📝 Key Features:
- Provides the **`ndarray`** object — a fast, memory-efficient multi-dimensional array.
- Vectorized operations — no need for slow Python `for` loops.
- Broadcasting — apply operations on arrays of different shapes.
- Backbone for Pandas, Matplotlib, scikit-learn, TensorFlow, etc.

### 📝 Why not just use Python lists?
NumPy arrays are much faster than lists for numeric work because they store data in contiguous memory and use optimized C code under the hood.

### 📝 Install & Import

In [1]:
# Install if needed (uncomment)
# !pip install numpy

import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.4.4


## 📌 **2. Creating Arrays**

### 📝 From Python lists

In [2]:
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D array:", arr1d)
print("2D array:\n", arr2d)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


### 📝 Built-in array creation functions

In [3]:
zeros = np.zeros((2, 3))          # array of zeros
ones = np.ones((2, 3))            # array of ones
full = np.full((2, 2), 7)         # array filled with a constant
identity = np.eye(3)              # identity matrix
arange = np.arange(0, 10, 2)      # like range(), but returns an array
linspace = np.linspace(0, 1, 5)   # 5 evenly spaced numbers between 0 and 1

print("zeros:\n", zeros)
print("ones:\n", ones)
print("full:\n", full)
print("identity:\n", identity)
print("arange:", arange)
print("linspace:", linspace)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
full:
 [[7 7]
 [7 7]]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


## 📌 **3. Array Attributes**

Every NumPy array has attributes describing its shape and data type.

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print("shape:", a.shape)     # (rows, cols)
print("ndim:", a.ndim)       # number of dimensions
print("size:", a.size)       # total number of elements
print("dtype:", a.dtype)     # data type of elements
print("itemsize:", a.itemsize, "bytes per element")

shape: (2, 3)
ndim: 2
size: 6
dtype: int64
itemsize: 8 bytes per element


## 📌 **4. Indexing and Slicing**

### 📝 1D indexing & slicing (same as Python lists)

In [5]:
a = np.array([10, 20, 30, 40, 50])

print("First element:", a[0])
print("Last element:", a[-1])
print("Slice [1:4]:", a[1:4])
print("Every other element:", a[::2])

First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Every other element: [10 30 50]


### 📝 2D indexing & slicing

In [6]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Element at row 1, col 2:", m[1, 2])
print("First row:", m[0, :])
print("First column:", m[:, 0])
print("Sub-matrix (rows 0-1, cols 1-2):\n", m[0:2, 1:3])

Element at row 1, col 2: 6
First row: [1 2 3]
First column: [1 4 7]
Sub-matrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]


### 📝 Boolean & fancy indexing

In [7]:
a = np.array([10, 15, 20, 25, 30, 35])

mask = a > 20
print("Mask:", mask)
print("Values > 20:", a[mask])

# Fancy indexing with a list of indices
print("Elements at positions [0, 2, 4]:", a[[0, 2, 4]])

# Modify values using a condition
a[a < 20] = 0
print("After zeroing values < 20:", a)

Mask: [False False False  True  True  True]
Values > 20: [25 30 35]
Elements at positions [0, 2, 4]: [10 20 30]
After zeroing values < 20: [ 0  0 20 25 30 35]


## 📌 **5. Reshaping Arrays**

In [8]:
a = np.arange(12)
print("Original:", a)

reshaped = a.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped)

flattened = reshaped.flatten()
print("Flattened back to 1D:", flattened)

transposed = reshaped.T
print("Transposed:\n", transposed)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened back to 1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## 📌 **6. Array Arithmetic and Broadcasting**

### 📝 Element-wise arithmetic

In [9]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("b / a:", b / a)
print("a ** 2:", a ** 2)

a + b: [11 22 33]
a - b: [ -9 -18 -27]
a * b: [10 40 90]
b / a: [10. 10. 10.]
a ** 2: [1 4 9]


### 📝 Broadcasting

Broadcasting lets NumPy apply operations between arrays of **different shapes** without writing loops.

In [10]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])
row = np.array([10, 20, 30])

print("Matrix + row (broadcast):\n", matrix + row)

scalar_result = matrix * 2
print("Matrix * scalar:\n", scalar_result)

Matrix + row (broadcast):
 [[11 22 33]
 [14 25 36]]
Matrix * scalar:
 [[ 2  4  6]
 [ 8 10 12]]


## 📌 **7. Mathematical & Statistical Functions**

In [11]:
data = np.array([12, 7, 3, 9, 15, 6, 21])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Std Dev:", np.std(data))
print("Variance:", np.var(data))
print("Min / Max:", np.min(data), "/", np.max(data))
print("Index of max (argmax):", np.argmax(data))
print("Cumulative sum:", np.cumsum(data))
print("Rounded sqrt:", np.round(np.sqrt(data), 2))

Sum: 73
Mean: 10.428571428571429
Median: 9.0
Std Dev: 5.6532454106883945
Variance: 31.95918367346939
Min / Max: 3 / 21
Index of max (argmax): 6
Cumulative sum: [12 19 22 31 46 52 73]
Rounded sqrt: [3.46 2.65 1.73 3.   3.87 2.45 4.58]


## 📌 **8. Linear Algebra Basics**

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix multiplication (A @ B):\n", A @ B)
print("Dot product:\n", np.dot(A, B))
print("Determinant of A:", np.linalg.det(A))
print("Inverse of A:\n", np.linalg.inv(A))
print("Transpose of A:\n", A.T)

Matrix multiplication (A @ B):
 [[19 22]
 [43 50]]
Dot product:
 [[19 22]
 [43 50]]
Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Transpose of A:
 [[1 3]
 [2 4]]


## 📌 **9. Random Numbers with `np.random`**

In [13]:
rng = np.random.default_rng(seed=42)   # seed for reproducibility

print("Random floats [0,1):", rng.random(5))
print("Random integers [0,100):", rng.integers(0, 100, size=5))
print("Normal distribution (mean=0, std=1):", np.round(rng.normal(0, 1, 5), 2))
print("Random choice from list:", rng.choice(["A", "B", "C", "D"], size=3))

Random floats [0,1): [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Random integers [0,100): [52 97 73 76 71]
Normal distribution (mean=0, std=1): [-0.02 -0.85  0.88  0.78  0.07]
Random choice from list: ['D' 'B' 'D']


## 📌 **10. Stacking, Splitting, Sorting, and Searching**

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("vstack (rows):\n", np.vstack([a, b]))
print("hstack (columns):", np.hstack([a, b]))
print("concatenate:", np.concatenate([a, b]))

c = np.arange(10)
parts = np.split(c, 5)
print("Split into 5 parts:", parts)

unsorted = np.array([5, 2, 9, 1, 7])
print("Sorted:", np.sort(unsorted))
print("Sort indices (argsort):", np.argsort(unsorted))
print("Where value > 4:", np.where(unsorted > 4))

vstack (rows):
 [[1 2 3]
 [4 5 6]]
hstack (columns): [1 2 3 4 5 6]
concatenate: [1 2 3 4 5 6]
Split into 5 parts: [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
Sorted: [1 2 5 7 9]
Sort indices (argsort): [3 1 0 4 2]
Where value > 4: (array([0, 2, 4]),)


## 📌 **11. Saving and Loading Arrays**

In [15]:
arr = np.array([1, 2, 3, 4, 5])

# Save/load in NumPy binary format
np.save("sample_array.npy", arr)
loaded = np.load("sample_array.npy")
print("Loaded from .npy:", loaded)

# Save/load as plain text (CSV-like)
np.savetxt("sample_array.csv", arr, delimiter=",")
loaded_txt = np.loadtxt("sample_array.csv", delimiter=",")
print("Loaded from .csv:", loaded_txt)

Loaded from .npy: [1 2 3 4 5]
Loaded from .csv: [1. 2. 3. 4. 5.]


## 🏭 **12. Hands-On Exercise: Factory Sensor Data**

Imagine a stamping press station logs a **vibration sensor reading every second for 10 seconds**. We'll use NumPy to analyze it — a common first step before feeding data into an anomaly-detection model.

### 🎯 Goals:
1. Simulate sensor readings.
2. Detect readings above a threshold (potential anomaly).
3. Compute summary statistics.

In [16]:
rng = np.random.default_rng(seed=1)

# Simulate 10 seconds of vibration sensor readings (normal around 2.0 mm/s)
sensor_readings = rng.normal(loc=2.0, scale=0.3, size=10)
sensor_readings = np.round(sensor_readings, 2)
print("Sensor readings (mm/s):", sensor_readings)

threshold = 2.5
anomalies = sensor_readings[sensor_readings > threshold]
anomaly_seconds = np.where(sensor_readings > threshold)[0]

print(f"\nThreshold: {threshold} mm/s")
print("Anomaly values:", anomalies)
print("Anomaly at second(s):", anomaly_seconds)

print(f"\nMean: {np.mean(sensor_readings):.2f} mm/s")
print(f"Max: {np.max(sensor_readings):.2f} mm/s")
print(f"Std Dev: {np.std(sensor_readings):.2f} mm/s")

Sensor readings (mm/s): [2.1  2.25 2.1  1.61 2.27 2.13 1.84 2.17 2.11 2.09]

Threshold: 2.5 mm/s
Anomaly values: []
Anomaly at second(s): []

Mean: 2.07 mm/s
Max: 2.27 mm/s
Std Dev: 0.19 mm/s


## 📝 **13. Practice Exercises**

Try these on your own:

1. Create a 5x5 NumPy array of random integers between 1 and 100. Find the row with the highest sum.
2. Given an array of temperatures in Celsius, convert them all to Fahrenheit using broadcasting (`F = C * 9/5 + 32`).
3. Create two 3x3 matrices and compute their matrix product and element-wise product. Explain the difference.
4. Simulate 100 "cycle time" readings (seconds) for a machine using `np.random.normal`. Count how many readings fall outside ±2 standard deviations from the mean (a simple outlier check).

## 🎯 **Conclusion**

In this notebook you learned:
- Creating and inspecting NumPy arrays
- Indexing, slicing, and reshaping
- Arithmetic operations and broadcasting
- Statistical and linear algebra functions
- Generating random numbers
- Stacking, splitting, sorting, and searching arrays
- Saving/loading arrays
- Applying NumPy to a simple factory sensor-data example

### Next: **Week 12 Supplement 2 — Pandas Full Tutorial**
Keep Practicing! 🚀